name: Android CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        # لا يوجد سطر كاش هنا نهائياً

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build APK (Manual Command)
      # لاحظ هنا: بنستخدم الـ flags اللي بتمنع الـ daemon والـ cache تماماً
      run: ./gradlew assembleDebug --no-daemon --no-build-cache --stacktrace
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Mirror-Scorpion-App
        path: app/build/outputs/apk/debug/app-debug.apk
